name: linter

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

permissions:
  contents: read

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.4"

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install Dependencies
        run: |
          composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
          bun install

      - name: Build project
        run: bun run build

      - name: Check TypeScript types
        run: bun run types

      - name: Run Pint Check
        run: vendor/bin/pint --test

      - name: Check code formatting
        run: bun run format:check

      - name: Lint code
        run: bun lint
